    openapi: 3.0.0
    info:
      title: Plato API
      description: Control all your social network accounts
      version: 1.0.0
    servers:
      - url: /
        description: Principal Server
    tags:
      - name: User
        description: API for requesting and returning users
      - name: Brand
        description: API for requesting and returning brands
      - name: Twitter
        description: API for Twitter Accounts
    paths:
      /user/create/:
        post:
          tags: [User]
          summary: Create an user if the given json is correct
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user-received'
          responses:
            '200':    # status code
              description: The user was created
            '500':
              description: Error
      /user/get/{userId}/:
        get:
          tags: [User]
          summary: Get a user by ID
          parameters:
            - in: path
              name: userId
              schema:
                type: string
              required: true
              description: UUID of the user to get
          responses:
            '200':    # status code
              description: The user was found
            '404':
              description: User was not found
            '500':
              description: Error
      /user/login/:
        post:
          tags: [User]
          summary: Check if password is correct and returns the user
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user-login'
          responses:
            '200':
              description: The login was succesfull
            '401':
              description: User email or password was incorrect
            '500':
              description: Error
      /brand/create/:
        post:
          tags: [Brand]
          summary: Create a new brand for a user
          security:
            - bearerAuth: []
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/brand-received'
          responses:
            '200':
              description: The brand was created
            '401':
              description: Access is not allowed
            '500':
              description: Error
      /brand/user/{userId}/:
        get:
          tags: [Brand]
          summary: Get a brand by user id
          security:
            - bearerAuth: []
          parameters:
            - in: path
              name: userId
              schema:
                type: string
              required: true
              description: UUID of the user owner of the brands
          responses:
            '200':    # status code
              description: The brand was found
            '404':
              description: Access is not allowed
            '500':
              description: Error
      /twitter/account/add/:
        post:
          tags: [Twitter]
          summary: Add a twitter Account
          security:
            - bearerAuth: []
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/twitter-oauth'
          responses:
            '200':
              description: The account was added
            '401':
              description: Access is not allowed
            '500':
              description: Error
      /twitter/tweet/schedule/:
        post:
          tags: [Twitter]
          summary: Schedule a Tweet
          security:
            - bearerAuth: []
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/twitter-tweet'
          responses:
            '200':
              description: The tweet was scheduled
            '401':
              description: Access is not allowed
            '500':
              description: Error
      /tweet/{accountId}/:
        get:
          tags: [Brand]
          summary: Get a brand by user id
          security:
            - bearerAuth: []
          parameters:
            - in: path
              name: accountId
              schema:
                type: string
              required: true
              description: UUID of the account owner of the tweets
            - in: query
              name: sinceDate
              schema:
                type: number
              description: Date since the tweets were scheduled
            - in: query
              name: limitDate
              schema:
                type: number
              description: Date limit to get the tweets
          responses:
            '200':    # status code
              description: The brand was found
            '404':
              description: Access is not allowed
            '500':
              description: Error
      /tweet/pusblish/:
        post:
          tags: [Twitter]
          summary: Publish tweets
          responses:
            '200':    # status code
              description: The user was found
            '404':
              description: User was not found
            '500':
              description: Error

    components:
      securitySchemes:
        bearerAuth:            # arbitrary name for the security scheme
          type: http
          scheme: bearer
          bearerFormat: JWT  
      schemas:
        user-received:
          type: object
          properties:
            user:
              type: object
              properties:
                userId:
                  type: string
                username:
                  type: string
                usermail:
                  type: string
                password:
                  type: string
        user-login:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
        brand-received:
          type: object
          properties:
            brand:
              type: object
              properties:
                id:
                  type: string
                userId:
                  type: string
                name:
                  type: string
                image:
                  type: string
        twitter-oauth:
          type: object
          properties:
            account:
              type: object
              properties:
                accountId:
                  type: string
                brandId:
                  type: string
                userId:
                  type: string
                oauthToken:
                  type: string
                oauthTokenSecret:
                  type: string
                oauthVerifier:
                  type: string
        twitter-tweet:
          type: object
          properties:
            tweet:
              type: object
              properties:
                tweetId:
                  type: string
                accountId:
                  type: string
                description:
                  type: string
                publicationDate:
                  type: integer
