# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Plato Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lint with flake8
        run: |
          pipenv flake8 . --count --show-source --statistics --max-line-length=125 --ignore E711
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: UnitTest with pytest
        run: |
          pipenv pytest -m unit
      - name: Integration Tests with pytest
        run: |
          pipenv pytest -m integration