# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Plato CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-eradicate
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics --max-line-length=125 --ignore E711
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv install pytest
      - name: UnitTest with pytest
        run: |
          pipenv run pytest -m unit
      - name: Integration Tests with pytest
        run: |
          pipenv run pytest -m integration